### PR TITLE
Fix Compat Issues due to String Network Refactor

### LINKED ISSUE #47: Crash midgame, possible TOPAddons incompat
```log
[22:38:40] [Netty Local Server IO #3/ERROR] [FML]: There was a critical exception handling a packet on channel theoneprobe
io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: 'void mcjty.theoneprobe.network.NetworkTools.writeString(io.netty.buffer.ByteBuf, java.lang.String)'
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:130)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:746)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1031)
	at io.netty.channel.Channel.write(Channel.java:272)
	at io.netty.channel.embedded.EmbeddedChannel.write(EmbeddedChannel.java:775)
	at io.github.lxgaming.sledgehammer.util.NetworkChannelHelper.writeAndFlush(NetworkChannelHelper.java:73)
	at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.writeAndFlush(FMLEmbeddedChannel.java:533)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250)
	at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:118)
	at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:109)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
	at java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at net.minecraft.util.Util.runTask(SourceFile:529)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:1447)
Caused by: java.lang.NoSuchMethodError: 'void mcjty.theoneprobe.network.NetworkTools.writeString(io.netty.buffer.ByteBuf, java.lang.String)'
	at io.github.drmanganese.topaddons.elements.ElementTankGauge.toBytes(ElementTankGauge.java:83)
	at mcjty.theoneprobe.apiimpl.ProbeInfo.writeElements(ProbeInfo.java:45)
	at mcjty.theoneprobe.apiimpl.elements.AbstractElementPanel.toBytes(AbstractElementPanel.java:58)
	at mcjty.theoneprobe.network.PacketReturnInfo.toBytes(PacketReturnInfo.java:36)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageCodec$2.encode(MessageToMessageCodec.java:85)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	... 19 more
```

### PR DESCRIPTION
**Pull request by IntegerLimit**
This PR fixes issues caused by https://github.com/strubium/TheOneSmeagle/commit/4e75197ab6c9191a6b3024d972058683774e08e6#diff-c5eaacb09eeae1823b5261fc42223359371f9cca0a3e260bd15b47b93bec7fe0, in which compat was broken with many mods due to the removal of the original read/write string methods in `NetworkTools`.

This PR adds those functions back (as deprecated), and restores the original distinction in the read/write string methods of null vs empty strings, in case mods depended on that behaviour. (This has only a tiny influence on packet size, which is worth it compared to potential compatibility issues)

Fixes #47

### CODE REVIEW

**Comment by IntegerLimit** [comment]
Marked as draft. I'm not 100% sure the impl of `varInt` allows for reading/writing negative integers, I need to test later.

**Comment by IntegerLimit** [comment]
Test successful.
